# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'


steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '../'

- task: ArchiveFiles@2
  displayName: Zip Site
  inputs:
    rootFolderOrFile: '$(Agent.BuildDirectory)/s/output' 
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true

# - script:  >-
#       curl
#       -H 'Authorization: Bearer $(netlifyAccessToken)' 
#       -H 'Content-Type: application/zip'
#       --data-binary '@$(Build.BuildId).zip'
#       https://api.netlify.com/api/v1/sites/$(netlifySiteId)/deploys
#   workingDirectory: '$(Build.ArtifactStagingDirectory)'
#   displayName: 'Upload to Netlify'