# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'


steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '../'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '../'
    customCommand: 'build --prod'
    customRegistry: 'useFeed'
    customFeed: 'b876ce2c-0e39-45d3-b649-13dc000e4211'

# - script:  >-
#       curl
#       -H 'Authorization: Bearer $(netlifyAccessToken)' 
#       -H 'Content-Type: application/zip'
#       --data-binary '@$(Build.BuildId).zip'
#       https://api.netlify.com/api/v1/sites/$(netlifySiteId)/deploys
#   workingDirectory: '$(Build.ArtifactStagingDirectory)'
#   displayName: 'Upload to Netlify'